"""empty message

Revision ID: 90fd83669a8b
Revises: 
Create Date: 2022-01-19 10:08:52.381510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fd83669a8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('Carros',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=70), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('preco', sa.String(length=70), nullable=True),
    sa.Column('kilometragem', sa.String(length=70), nullable=True),
    sa.Column('cor', sa.String(length=70), nullable=True),
    sa.Column('quantidade', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Motos',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=70), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('preco', sa.String(length=70), nullable=True),
    sa.Column('kilometragem', sa.String(length=70), nullable=True),
    sa.Column('cor', sa.String(length=70), nullable=True),
    sa.Column('quantidade', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nome'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Carrinho de Compras',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=True),
    sa.Column('carros_id', sa.Integer(), nullable=True),
    sa.Column('motos_id', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('entregou', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carros_id'], ['Carros.id'], ),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['motos_id'], ['Motos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carrinho de Compras')
    op.drop_table('entregas')
    op.drop_table('Motos')
    op.drop_table('Carros')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
